<?php

namespace App\Http\Requests\Assignment;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            'number' => ['required', 'string', 'size:4', 'regex:/^\d{4}$/'],
            'number_prefix' => ['required', 'integer', 'digits:2'],
            'number_note' => ['nullable', 'string'],
            'number_index_id' => ['required', 'integer', 'exists:number_indexes,id'],
            'in_date' => ['required', 'date'],
            'base_id' => ['required', 'integer', 'exists:basics,id'],
            'base_number' => ['nullable', 'string'],
            'base_date' => ['nullable', 'date'],
            'object' => ['nullable', 'string'],
            'object_birthday' => ['nullable', 'date'],
            'citizenship' => ['nullable', 'boolean'],
            'judging' => ['nullable', 'boolean'],
            'ethnicity' => ['nullable', 'boolean'],
            'itt' => ['nullable', 'boolean'],
            'budget' => ['nullable', 'boolean'],
            'bdsm' => ['nullable', 'boolean'],
            'ptsm' => ['nullable', 'boolean'],
            'quickly' => ['nullable', 'boolean'],
            'transit' => ['nullable', 'boolean'],
            'outside_zone' => ['nullable', 'boolean'],
            'og' => ['nullable', 'boolean'],
            'series' => ['nullable', 'boolean'],
            'without_execution' => ['nullable', 'boolean'],
            'executed_date' => ['nullable', 'date'],
            'page' => ['nullable', 'integer'],
            'doc_control' => ['nullable', 'boolean'],
            'audio_control' => ['nullable', 'boolean'],
            'track_control' => ['nullable', 'boolean'],
            'together_control' => ['nullable', 'boolean'],
            'employer_defect' => ['nullable', 'string'],
            'note' => ['nullable', 'string'],
            'use_video' => ['nullable', 'boolean'],
            'use_photo' => ['nullable', 'boolean'],
            'use_audio' => ['nullable', 'boolean'],
            'for_us' => ['nullable', 'boolean'],
            'place_work' => ['nullable', 'boolean'],
            'relation' => ['nullable', 'integer'],
            'ident_relation' => ['nullable', 'integer'],
            'is_fail' => ['nullable', 'boolean'],
            'region' => ['nullable', 'boolean'],
            'bio' => ['nullable', 'boolean'],
            'copy' => ['nullable', 'boolean'],
            'spravka' => ['nullable', 'boolean'],
            'photo_device' => ['nullable', 'integer'],
            'photo_device_photo' => ['nullable', 'integer'],
            'photo_device_video' => ['nullable', 'integer'],
            'photo_device_audio' => ['nullable', 'integer'],
            'video_device' => ['nullable', 'integer'],
            'video_device_photo' => ['nullable', 'integer'],
            'video_device_video' => ['nullable', 'integer'],
            'video_device_audio' => ['nullable', 'integer'],
            'audio_device' => ['nullable', 'integer'],
            'audio_device_audio' => ['nullable', 'integer'],
            'input_data' => ['nullable', 'integer'],
            'persons' => ['nullable', 'integer'],
            'firms' => ['nullable', 'integer'],
            'transport' => ['nullable', 'integer'],
            'address' => ['nullable', 'integer'],
            'photo' => ['nullable', 'integer'],
            'scheme' => ['nullable', 'boolean'],
            'spr_return' => ['nullable', 'date'],
            'spr_prevent_crime' => ['nullable', 'string'],
            'spr_prevent' => ['nullable', 'integer'],
            'spr_solved_crime' => ['nullable', 'string'],
            'spr_solved' => ['nullable', 'integer'],
            'spr_search_crime' => ['nullable', 'string'],
            'spr_search' => ['nullable', 'integer'],
            'spr_search_person' => ['nullable', 'string'],
            'spr_search_date' => ['nullable', 'date'],
            'spr_dou' => ['nullable', 'string'],
            'spr_dou_date' => ['nullable', 'date'],
            'spr_crim_liability' => ['nullable', 'integer'],
            'spr_adm_liability' => ['nullable', 'integer'],
            'spr_identity_established' => ['nullable', 'integer'],
            'spr_connection' => ['nullable', 'integer'],
            'spr_live_place' => ['nullable', 'integer'],
            'spr_work_place' => ['nullable', 'integer'],
            'spr_crim_groups' => ['nullable', 'integer'],
            'spr_crim_groups_count' => ['nullable', 'integer'],
            'spr_oper_accounting' => ['nullable', 'integer'],
            'spr_result_another' => ['nullable', 'string'],
            'gun' => ['nullable', 'integer'],
            'bullet' => ['nullable', 'integer'],
            'bang' => ['nullable', 'numeric'],
            'drug' => ['nullable', 'numeric'],
            'money' => ['nullable', 'numeric'],
            'car' => ['nullable', 'integer'],
            'form' => ['nullable', 'integer'],
            'tehn' => ['nullable', 'integer'],
            'autor_id' => ['required', 'integer', 'exists:users,id'],
            'main_crime_id' => ['required', 'integer', 'exists:crimes,id'],
            'additional_crimes_ids' => ['nullable', 'array', 'exists:crimes,id'],
            'employer_id' => ['required', 'integer', 'exists:employers,id'],
            'object_type_id' => ['required', 'integer', 'exists:object_types,id'],
            'execut_id' => ['nullable', 'integer', 'exists:users,id'],
        ];
    }

    public function messages()
    {
        return [
            'number.required' => 'Номер обязателен',
            'number.string' => 'Номер - 4 числа',
            'number.size' => 'Номер - 4 числа',
            'number.regex' => 'Номер - 4 числа',
            'number_prefix.required' => 'Год к номеру обязателен',
            'number_prefix.integer' => 'Год к номеру состоит только из чисел',
            'number_prefix.digits' => 'Год к номеру должен содержать 2 цифры',
            'number_index_id.required' => 'Выберите индекс номера',
            'in_date.required' => 'Укажите дату',
            'in_date.date' => 'Укажите дату',
            'base_id.required' => 'Выберите основание',
            'base_date.date' => 'Введите корректный формат даты основания',
            'object_birthday.date' => 'Введите корректный формат даты',
            'executed_date.date' => 'Введите корректный формат даты исп.',
            'page.integer' => 'Кол-во листов - число',
            'relation.integer' => 'Кол-во выявл. - число',
            'ident_relation.integer' => 'Кол-во уст. - число',
            'photo_device.integer' => 'Кол-во использ. - число',
            'photo_device_photo.integer' => 'Кол-во фото - число',
            'photo_device_video.integer' => 'Кол-во видео - число',
            'photo_device_audio.integer' => 'Кол-во аудио  - число',
            'video_device.integer' => 'Кол-во использ. - число',
            'video_device_photo.integer' => 'Кол-во фото - число',
            'video_device_video.integer' => 'Кол-во видео - число',
            'video_device_audio.integer' => 'Кол-во аудио - число',
            'audio_device.integer' => 'Кол-во использ. - число',
            'audio_device_audio.integer' => 'Кол-во аудио - число',
            'input_data.integer' => 'Кол-во перв. инф - число',
            'persons.integer' => 'Кол-во лиц - число',
            'firms.integer' => 'Кол-во лиц - число',
            'transport.integer' => 'Кол-во трансп. ср-в - число',
            'address.integer' => 'Кол-во адресов - число',
            'photo.integer' => 'Кол-во фото - число',
            'spr_return.date' => 'Введите корректный формат даты',
            'spr_prevent.integer' => 'Кол-во прест. - число',
            'spr_solved.integer' => 'Кол-во прест. - число',
            'spr_search.integer' => 'Кол-во лиц - число',
            'spr_search_date.date' => 'Введите корректный формат даты',
            'spr_dou_date.date' => 'Введите корректный формат даты реализ.',
            'spr_crim_liability.integer' => 'Кол-во лиц - число',
            'spr_adm_liability.integer' => 'Кол-во лиц - число',
            'spr_identity_established.integer' => 'Кол-во спос-х уст. - число',
            'spr_connection.integer' => 'Число',
            'spr_live_place.integer' => 'Число',
            'spr_work_place.integer' => 'Число',
            'spr_crim_groups.integer' => 'Число',
            'spr_crim_groups_count.integer' => 'Число',
            'spr_oper_accounting.integer' => 'Число',
            'gun.integer' => 'Число',
            'bullet.integer' => ' Число',
            'bang.numeric' => 'Число',
            'drug.numeric' => 'Число',
            'money.numeric' => 'Число',
            'car.integer' => 'Число',
            'form.integer' => 'Число',
            'tehn.integer' => 'Число',
            'main_crime_id.required' => 'Выберите прест.',
            'employer_id.required' => 'Выберите заказ.',
            'object_type_id.required' => 'Выберите тип',
        ];
    }
}
